### ISSUE TITLE
adding geodesic:true option

### ISSUE THREAD

**Issue by neogis-de** [jorix/OL-DynamicMeasure#8]
Hello. I just added an option to use "geodesic:true" in my fork of your repository:
http://rawgit.com/neogis-de/OL-DynamicMeasure/geodesic/examples/measure-dynamic.html
( As answer to a question on stackexchange: https://gis.stackexchange.com/questions/164628/why-does-not-equal-computing-line-in-openlayers-with-arcgis-when-i-use-measu?noredirect=1#comment245936_164628 )

I was just wondering if you are interested in adding this to your example as well?

**Comment by jorix** [comment]
@neogis-de :
I share your concern about the correct use of geodetic measurements but I do not agree to convert the example in order to compare the use or not of geodetic measurements. It is for these reasons that I've only added 'geodesic:true' on js code with a comments about it, see d502b1f76cf3b98bd9cfdd38a9a5748bfe1e9820 .

Thank you very much for highlighting this important detail.
